{% set version = "0.1.2" %}

package:
  name: dante_ltr
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante_ltr/archive/refs/tags/{{ version }}.tar.gz
  sha256: 994ebd99776a8a313f5adf67e0cf8218a8fb6709a25bbb88e5e316033157531a
requirements:
  run:
    - r-optparse
    - blast
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-rtracklayer
test:
  commands:
    - extract_putative_ltr.R --help

about:
  dev_url: https://github.com/kavonrtep/dante_ltr
  license: GNU GPL v3
  license_file: LICENSE
  summary: DANTE_LTR is a program for finding full-length LTR retrotranspsons using Domain based ANnotation of Transposable Wlements

extra:
  copy_test_source_files: true
  final: true

