{% set version = "0.1.6.0" %}

package:
  name: dante_ltr
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante_ltr/archive/refs/tags/{{ version }}.tar.gz
  sha256: 75b9a704cbeb1481eeeee635f55f246e90561f0dcaba563706f79494f29dba22
requirements:
  run:
    - r-optparse
    - blast
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-rtracklayer
test:
  commands:
    - extract_putative_ltr.R --help

about:
  dev_url: https://github.com/kavonrtep/dante_ltr
  license: GNU GPL v3
  license_file: LICENSE
  summary: DANTE_LTR is a program for finding full-length LTR retrotranspsons using Domain based ANnotation of Transposable elements

extra:
  copy_test_source_files: true
  final: true

